### ISSUE TITLE
Frontier Labs SD Card Serial Number Encoding

### ISSUE THREAD

**Issue by noahmacaskill** [ecoacoustics/known-problems#1]
# Incorrect SD Card Serial Number Encoded into FLAC Vorbis Comment Block for Frontier Labs Recordings
Within the Vorbis Comment section of FLAC files, Frontier Labs identify the SD Card CID, represented as a 16-byte hexadecimal string. The SD Card serial number can be found in bytes 10-13 of that hex string.

On two test recordings made using different SD cards there seems to be a bug in which the SD Card serial number from the log file isn't matching the serial number encoded into the CID. As shown in the table, the bytes are matching except for the two most significant bytes in the CID serial number (the serial number from the log file is given in decimal and has been converted). It appears the CID serial numbers' two most significant bytes should instead be 0s.

These recordings were both taken with BAR-LTs running firmware version 3.30.

|Recording | Log file serial number | Log file serial number with hex conversion | CID serial number |
|------------------|--------------|-------------|--------|
| Test Recording 1 | 8041328 | 7AB370 | 437AB370 |
| Test Recording 2 | 11217428 | AB2A14  | 88AB2A14 |

**Comment by atruskie** [comment]
Thanks for report!

@noahmacaskill can you leave a link to some demo files please (place it on some shared cloud storage)

- logs of files
- demo files that exhibit the problem (as many samples from as many sensors and memory card combinations as you ahve)
- a license to release the files (preferrably CC BY 4)
- an attribution for the files

@ninascarpelli can you write this up into a known issue please. When Noah has provided the files we'll add them to our demo area.

Then we'll contact FL and see what they can say about the bug.

**Comment by atruskie** [comment]
I've also arranged for the manager from our lab (@tuckerdi) to see if they can reproduce this on one of our sensors.

**Comment by noahmacaskill** [comment]
We've done 3 more tests (up to a total of 5 now), they all seem to have the same issue. [Here](https://drive.google.com/drive/folders/1qC-0vopl03x3_jW2Py_2fAijKukRMWPN?usp=sharing) is a Google Drive link to all 5 of them.

**Comment by noahmacaskill** [comment]
Just to add a little more to this. I've been going under the assumption that the value in the log file is the actual SD card serial number, but this may not be the case. We tried to retrieve the serial numbers from the SD cards themselves earlier today using [this website](https://www.diskpart.com/articles/read-sd-card-serial-number-windows-1984.html) as a guide. We ended up finding numbers that didn't correlate to what we found in the log file or in the CID which has left me a bit puzzled.

It seems possible that the numbers from both the CID and log file are wrong, but maybe the numbers we pulled from the SD cards themselves are wrong, tough to say.

**Comment by atruskie** [comment]
I think if our lab can reproduce the problem then we won't need too much rigor from you.

It's actually super hard to read these CID numbers on a modern PC. AFAIK the information isn't exposed over the USB protocol, so any SD card reader that connects via USB (instead of PCIe) won't be able to read the number (this increasingly includes laptops too, which used to use PCIe but now often just use USB internally as well).

**Comment by atruskie** [comment]
Ok @ninascarpelli wrote this up into an actual problem document (see https://github.com/ecoacoustics/known-problems/blob/main/frontier_labs/FL007.md), we'll keep adding to it and we'll contact FL for comment. 

Closed in https://github.com/ecoacoustics/known-problems/commit/814aa0413de3f66bd8f80af2a419afcfdc6acff2
